version: '3.1'

services:

  nginx:
    container_name: cf-nginx
    build:
      context: docker/config/nginx
    ports:
      - 8080:80
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: cf-php
    build:
      context: docker/config/php
    ports:
      - 9000:9000
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/config/php/php.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

  mysql:
    container_name: cf-mysql
    build:
      context: docker/config/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cf
    working_dir: /application
    volumes:
      - .:/application